apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor-crd.yaml
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - pdb.yaml
  - pvc.yaml
  - rbac.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
