apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-service-account
  namespace: nginx-system
  labels:
    app: nginx-proxy
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-role
  labels:
    app: nginx-proxy
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-role-binding
  labels:
    app: nginx-proxy
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: nginx-system
roleRef:
  kind: ClusterRole
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
