# Pod Disruption Budgets untuk Application Services
# PDB memastikan minimal sejumlah pod tetap running saat maintenance/update

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: suma-ecommerce-admin-pdb
  namespace: suma-ecommerce-admin
spec:
  minAvailable: 1  # Minimal 1 pod harus running (dari 2 total pods)
  selector:
    matchLabels:
      app: suma-ecommerce-admin

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: suma-ecommerce-client-pdb
  namespace: suma-ecommerce-client
spec:
  minAvailable: 1  # Minimal 1 pod harus running (dari 2 total pods)
  selector:
    matchLabels:
      app: suma-ecommerce-client

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: suma-office-pdb
  namespace: suma-office
spec:
  minAvailable: 1  # Minimal 1 pod harus running (dari 2 total pods)
  selector:
    matchLabels:
      app: suma-office
      environment: production

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: nginx-system
spec:
  minAvailable: 1  # Minimal 1 nginx pod harus running
  selector:
    matchLabels:
      app: nginx-proxy

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: haproxy-pdb
  namespace: haproxy
spec:
  minAvailable: 1  # Minimal 1 haproxy pod harus running
  selector:
    matchLabels:
      app: haproxy-loadbalancer
